/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: example.swigcxx

package example

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_example_fe57d0301a1c3822(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_example_fe57d0301a1c3822(swig_intgo arg1);
extern uintptr_t _wrap_new_Example_example_fe57d0301a1c3822(swig_intgo arg1);
extern swig_intgo _wrap_Example_GetNumber_example_fe57d0301a1c3822(uintptr_t arg1);
extern void _wrap_delete_Example_example_fe57d0301a1c3822(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_example_fe57d0301a1c3822(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_example_fe57d0301a1c3822(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrExample uintptr

func (p SwigcptrExample) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample) SwigIsExample() {
}

func NewExample(arg1 int) (_swig_ret Example) {
	var swig_r Example
	_swig_i_0 := arg1
	swig_r = (Example)(SwigcptrExample(C._wrap_new_Example_example_fe57d0301a1c3822(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrExample) GetNumber() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Example_GetNumber_example_fe57d0301a1c3822(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteExample(arg1 Example) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Example_example_fe57d0301a1c3822(C.uintptr_t(_swig_i_0))
}

type Example interface {
	Swigcptr() uintptr
	SwigIsExample()
	GetNumber() (_swig_ret int)
}


