/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: example.swigcxx */


/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "libexample.so"

#include "runtime.h"
#include "cgocall.h"

#pragma dataflag 16
static void *cgocall = runtime·cgocall;
#pragma dataflag 16
void *·_cgo_runtime_cgocall = &cgocall;


#pragma dynimport _wrap_Swig_free_example_fe57d0301a1c3822 _wrap_Swig_free_example_fe57d0301a1c3822 ""
#pragma cgo_import_static _wrap_Swig_free_example_fe57d0301a1c3822
extern void _wrap_Swig_free_example_fe57d0301a1c3822(void*);
uintptr ·_wrap_Swig_free_example_fe57d0301a1c3822 = (uintptr)_wrap_Swig_free_example_fe57d0301a1c3822;




#pragma dynimport _wrap_Swig_malloc_example_fe57d0301a1c3822 _wrap_Swig_malloc_example_fe57d0301a1c3822 ""
#pragma cgo_import_static _wrap_Swig_malloc_example_fe57d0301a1c3822
extern void _wrap_Swig_malloc_example_fe57d0301a1c3822(void*);
uintptr ·_wrap_Swig_malloc_example_fe57d0301a1c3822 = (uintptr)_wrap_Swig_malloc_example_fe57d0301a1c3822;




#pragma dynimport _wrap_new_Example_example_fe57d0301a1c3822 _wrap_new_Example_example_fe57d0301a1c3822 ""
#pragma cgo_import_static _wrap_new_Example_example_fe57d0301a1c3822
extern void _wrap_new_Example_example_fe57d0301a1c3822(void*);
uintptr ·_wrap_new_Example_example_fe57d0301a1c3822 = (uintptr)_wrap_new_Example_example_fe57d0301a1c3822;




#pragma dynimport _wrap_Example_GetNumber_example_fe57d0301a1c3822 _wrap_Example_GetNumber_example_fe57d0301a1c3822 ""
#pragma cgo_import_static _wrap_Example_GetNumber_example_fe57d0301a1c3822
extern void _wrap_Example_GetNumber_example_fe57d0301a1c3822(void*);
uintptr ·_wrap_Example_GetNumber_example_fe57d0301a1c3822 = (uintptr)_wrap_Example_GetNumber_example_fe57d0301a1c3822;




#pragma dynimport _wrap_delete_Example_example_fe57d0301a1c3822 _wrap_delete_Example_example_fe57d0301a1c3822 ""
#pragma cgo_import_static _wrap_delete_Example_example_fe57d0301a1c3822
extern void _wrap_delete_Example_example_fe57d0301a1c3822(void*);
uintptr ·_wrap_delete_Example_example_fe57d0301a1c3822 = (uintptr)_wrap_delete_Example_example_fe57d0301a1c3822;




