/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: example.swigcxx

package example

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

var _wrap_Swig_free_example_fe57d0301a1c3822 unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_example_fe57d0301a1c3822, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_example_fe57d0301a1c3822 unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_example_fe57d0301a1c3822, _swig_p)
	return
}
type SwigcptrExample uintptr

func (p SwigcptrExample) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample) SwigIsExample() {
}

var _wrap_new_Example_example_fe57d0301a1c3822 unsafe.Pointer

func _swig_wrap_new_Example(base int) (_ SwigcptrExample) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example_example_fe57d0301a1c3822, _swig_p)
	return
}

func NewExample(arg1 int) (_swig_ret Example) {
	return _swig_wrap_new_Example(arg1)
}

var _wrap_Example_GetNumber_example_fe57d0301a1c3822 unsafe.Pointer

func _swig_wrap_Example_GetNumber(base SwigcptrExample) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example_GetNumber_example_fe57d0301a1c3822, _swig_p)
	return
}

func (arg1 SwigcptrExample) GetNumber() (_swig_ret int) {
	return _swig_wrap_Example_GetNumber(arg1)
}

var _wrap_delete_Example_example_fe57d0301a1c3822 unsafe.Pointer

func _swig_wrap_delete_Example(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Example_example_fe57d0301a1c3822, _swig_p)
	return
}

func DeleteExample(arg1 Example) {
	_swig_wrap_delete_Example(arg1.Swigcptr())
}

type Example interface {
	Swigcptr() uintptr
	SwigIsExample()
	GetNumber() (_swig_ret int)
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

